{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.denial;
in
{
  options.programs.denial = {
    enable = lib.mkEnableOption "Denial, a Flutter-native Wayland compositor";

    package = lib.mkPackageOption pkgs "denial" { };

    # Tools the shell and session launch by name, e.g. nmcli, powerprofilesctl
    # or lact. They are only put on the session PATH, matching the optional
    # dependencies of the upstream packages.
    extraRuntimePackages = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = [ ];
      example = lib.literalExpression ''
        with pkgs; [
          networkmanager
          upower
          power-profiles-daemon
        ]
      '';
      description = "Extra packages to expose on the Denial session PATH.";
    };

    user = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Optional session user to add to video/input/render/seat groups. Leave null to manage groups manually.";
    };

    outputs = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = ''Lines for /etc/denial/outputs.conf (system template; copied to ~/.config/denial/outputs.conf on first login). Empty = auto-discover.'';
    };

    extraOutputsConf = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra raw lines appended to /etc/denial/outputs.conf.";
    };

    extraSessionConf = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = { DENIAL_RUST_LOG = "deniald=debug"; };
      description = "Extra KEY=VALUE entries for /etc/denial/session.conf.";
    };
  };
  config = lib.mkIf cfg.enable (let
    sessionConf = lib.concatStringsSep "\n" (lib.flatten [
      "# Generated by NixOS. Sourced by denial-session at session start."
      (lib.mapAttrsToList (n: v: "${n}=${v}") cfg.extraSessionConf)
    ]);
    outputsConf = lib.concatStringsSep "\n" (lib.flatten [
      "# Generated by NixOS. Copied to ~/.config/denial/outputs.conf on first login."
      cfg.outputs
      (lib.optionalString (cfg.extraOutputsConf != "") cfg.extraOutputsConf)
    ]);
  in {
    environment.systemPackages = [ cfg.package ] ++ cfg.extraRuntimePackages;

    # Lets display managers discover the packaged wayland-sessions entry.
    services.displayManager.sessionPackages = [ cfg.package ];

    # deniald starts and stops denial-session.target through the systemd
    # user manager on its own; installing the packaged unit is enough.
    systemd.packages = [ cfg.package ];

    # The lock screen authenticates through PAM using the service named by
    # DENIAL_PAM_SERVICE (defaults to "login" upstream).
    security.pam.services.denial = { };
    environment.sessionVariables.DENIAL_PAM_SERVICE = "denial";

    environment.etc."denial/session.conf".text = sessionConf + "\n";
    environment.etc."denial/outputs.conf".text = outputsConf + "\n";

    users.groups.video = { };
    users.groups.input = { };
    users.groups.render = { };
    users.groups.seat = { };
    users.users = lib.optionalAttrs (cfg.user != null) {
      ${cfg.user} = { extraGroups = [ "video" "input" "render" "seat" ]; };
    };
    hardware.graphics.enable = lib.mkDefault true;
    security.rtkit.enable = lib.mkDefault true;

    # Base Wayland session integration, same defaults the niri module gets
    # from wayland-session.nix: Polkit for power/network portals, dconf for
    # the GTK portal, Xwayland for the X clients the session launcher puts
    # on PATH.
    services.graphical-desktop.enable = lib.mkDefault true;
    security.polkit.enable = lib.mkDefault true;
    programs.dconf.enable = lib.mkDefault true;
    programs.xwayland.enable = lib.mkDefault true;

    xdg.portal = {
      enable = lib.mkDefault true;
      extraPortals = with pkgs; [
        xdg-desktop-portal-gtk
        xdg-desktop-portal-wlr
      ];
      # Mirrors the upstream denial-portals.conf: GTK handles the generic
      # interfaces, Denial implements the Settings interface itself since
      # 0.2.16, and the wlroots backend consumes Denial's screencopy
      # protocol for ScreenCast and Screenshot.
      config.denial = {
        default = [ "gtk" ];
        "org.freedesktop.impl.portal.Settings" = [
          "denial"
          "gtk"
        ];
        "org.freedesktop.impl.portal.ScreenCast" = "wlr";
        "org.freedesktop.impl.portal.Screenshot" = "wlr";
      };
    };

    # Denial does not implement zwlr-layer-shell, so xdg-desktop-portal-wlr
    # must use the Zenity chooser shipped in the package instead of slurp.
    environment.etc."xdg/xdg-desktop-portal-wlr/Denial".source =
      "${cfg.package}/share/xdg-desktop-portal-wlr/Denial";
  });
}
