{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.denial;
in
{
  options.programs.denial = {
    enable = lib.mkEnableOption "Denial, a Flutter-native Wayland compositor";

    # One switch for where the Flutter components come from. It moves the
    # default of both packages below so they cannot disagree: a source-built
    # compositor paired with a prebuilt toolchain (or the other way round) would
    # mix two engine builds that were never meant to run against each other.
    #
    # It only sets defaults. Defining `package` or `uiDevelopment.package`
    # explicitly still wins, so unusual combinations remain possible.
    useSource = lib.mkOption {
      type = lib.types.bool;
      default = false;
      example = true;
      description = ''
        Whether to build the Flutter components Denial bundles (the engine,
        the shell and the settings app) from source instead of taking
        upstream's prebuilt artifacts.

        Enabling this changes the default of {option}`package` and
        {option}`uiDevelopment.package` to their `-source` counterparts.
        The Rust side of Denial is built from source either way.

        Required on aarch64: upstream publishes prebuilt artifacts for
        x86_64 only, so the prebuilt packages refuse to evaluate there.
      '';
    };

    package = lib.mkPackageOption pkgs "denial" {
      default = if cfg.useSource then [ "denial-source" ] else [ "denial" ];
      extraDescription = ''
        Defaults to `pkgs."denial-source"` when
        {option}`useSource` is enabled.
      '';
    };

    # Deliberately decoupled from the compositor: nothing pulls the toolchain
    # in on its own, and enabling Denial does not install it. It is a
    # development dependency for people editing Denial's UI, not something a
    # session needs to start.
    uiDevelopment = {
      enable = lib.mkEnableOption "the Denial UI development toolchain";

      package = lib.mkPackageOption pkgs "denial-ui-development" {
        # Keyed off the compositor actually in use, not off `useSource`, so a
        # hand-written `package` still gets a toolchain built the same way.
        # `or false` covers packages that do not carry the marker (a local
        # override, say) by falling back to upstream's default.
        default =
          if cfg.package.flutterFromSource or false then
            [ "denial-ui-development-source" ]
          else
            [ "denial-ui-development" ];
        extraDescription = ''
          Installed only when {option}`enable` is set. Follows
          {option}`package`: a source-built compositor gets
          `pkgs."denial-ui-development-source"`, a prebuilt one gets the
          prebuilt toolchain.
        '';
      };
    };

    # Tools the shell and session launch by name, e.g. nmcli, powerprofilesctl
    # or lact. They are only put on the session PATH, matching the optional
    # dependencies of the upstream packages.
    extraRuntimePackages = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = [ ];
      example = lib.literalExpression ''
        with pkgs; [
          networkmanager
          upower
          power-profiles-daemon
        ]
      '';
      description = "Extra packages to expose on the Denial session PATH.";
    };

    user = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Optional session user to add to video/input/render/seat groups. Leave null to manage groups manually.";
    };

    extraSessionConf = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = { DENIAL_RUST_LOG = "deniald=debug"; };
      description = "Extra KEY=VALUE entries for /etc/denial/session.conf.";
    };
  };
  config = lib.mkIf cfg.enable (let
    sessionConf = lib.concatStringsSep "\n" (lib.flatten [
      "# Generated by NixOS. Sourced by denial-session at session start."
      # Kept out of `environment.sessionVariables`, which would export it into
      # every PAM session on the machine (ssh, tty, other desktop environments)
      # and not just the Denial one.
      #
      # Listed before extraSessionConf so an explicit entry there wins.
      "DENIAL_PAM_SERVICE=denial"
      # The shell asks deniald to spawn this exact path; upstream defaults to
      # /usr/bin/denial-settings, which does not exist on NixOS. Every variant
      # of the package ships bin/denial-settings, and deniald's spawned
      # children inherit the session environment, so the wrapper's
      # LD_LIBRARY_PATH reaches the settings binary too.
      "DENIAL_SETTINGS_BINARY=${cfg.package}/bin/denial-settings"
      (lib.mapAttrsToList (n: v: "${n}=${v}") cfg.extraSessionConf)
    ]);

  in {
    environment.systemPackages =
      [ cfg.package ]
      ++ lib.optional cfg.uiDevelopment.enable cfg.uiDevelopment.package
      ++ cfg.extraRuntimePackages;

    # Lets display managers discover the packaged wayland-sessions entry.
    services.displayManager.sessionPackages = [ cfg.package ];

    # deniald starts and stops denial-session.target through the systemd
    # user manager on its own; installing the packaged unit is enough.
    systemd.packages = [ cfg.package ];

    # The lock screen authenticates through PAM using the service named by
    # DENIAL_PAM_SERVICE (defaults to "login" upstream).
    security.pam.services.denial = { };

    environment.etc."denial/session.conf".text = sessionConf + "\n";

    users.groups.video = { };
    users.groups.input = { };
    users.groups.render = { };
    users.groups.seat = { };
    users.users = lib.optionalAttrs (cfg.user != null) {
      ${cfg.user} = { extraGroups = [ "video" "input" "render" "seat" ]; };
    };
    hardware.graphics.enable = lib.mkDefault true;
    security.rtkit.enable = lib.mkDefault true;

    # Base Wayland session integration, same defaults the niri module gets
    # from wayland-session.nix: Polkit for power/network portals, dconf for
    # the GTK portal, Xwayland for the X clients the session launcher puts
    # on PATH.
    services.graphical-desktop.enable = lib.mkDefault true;
    security.polkit.enable = lib.mkDefault true;
    programs.dconf.enable = lib.mkDefault true;
    programs.xwayland.enable = lib.mkDefault true;

    xdg.portal = {
      enable = lib.mkDefault true;
      extraPortals = with pkgs; [
        xdg-desktop-portal-gtk
        xdg-desktop-portal-wlr
      ];
      # The package ships upstream's routing as
      # share/xdg-desktop-portal/denial-portals.conf: GTK for the generic
      # interfaces, Denial for the Settings interface it implements itself
      # since 0.2.16, and the wlroots backend for ScreenCast/Screenshot,
      # which consumes Denial's screencopy protocol. Registering the package
      # here exposes that file through XDG_DATA_DIRS, the same way GNOME and
      # KDE ship their own -portals.conf.
      #
      # Deliberately not xdg.portal.config: that would land in
      # /etc/xdg/xdg-desktop-portal/denial-portals.conf, and portals.conf(5)
      # reads only the first file found while ranking every config directory
      # above every data directory. Such a copy would shadow the packaged one
      # and drift silently whenever upstream changes its routing.
      configPackages = [ cfg.package ];
    };

    # Denial does not implement zwlr-layer-shell, so xdg-desktop-portal-wlr
    # must use the Zenity chooser shipped in the package instead of slurp.
    environment.etc."xdg/xdg-desktop-portal-wlr/Denial".source =
      "${cfg.package}/share/xdg-desktop-portal-wlr/Denial";
  });
}
